### ISSUE TITLE
Verbesserungsvorschlag

### ISSUE THREAD

**Issue by TheLordJakob** [PaulRaffer/Online-Poker#17]
Die Auswahl was man tun möchte könnte als Pop-Up erscheinen. Es wäre damit möglich, dass man nicht scrollen muss um seinen Zug zu machen.

**Comment by PaulRaffer** [comment]
Gute Idee!

**Comment by TheLordJakob** [comment]
dann könntest auch anzeigen um wieviel man min. erhöhen kann

**Comment by PaulRaffer** [comment]
> 
> 
> Die Auswahl was man tun möchte könnte als Pop-Up erscheinen. Es wäre damit möglich, dass man nicht scrollen muss um seinen Zug zu machen.

Ein Pop-Up würde die anderen Spieler und deren Gebote überdecken. Ich werde mir etwas anderes überlegen um das Problem zu lösen. Z. B. könnte man die Aktionsauswahl an den Beginn der Seite verlegen. Auch das Anzeigen der Spieler in zwei Spalten (#20), könnte dazu führen, dass weniger gescrollt werden muss.

**Comment by PaulRaffer** [comment]
The action selection is now fixed at the bottom  (#21)
